
# Loosely modeled on the starter submit file here:
#   http://chtc.cs.wisc.edu/helloworld.shtml

# Type of job we will be running
universe = vanilla

# Resource requirements we need for this job
request_cpus = 1
request_memory = 2GB
request_disk = 1GB

# Specify the policy for moving files between the execute
# and submit environments
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Finally, which files to transfer.  We'll be using CUDA
# and parboil-cutcp for this example.
# NOTE: the gpgpu-sim configuration files are a macro; to be
# defined later.
initialdir = $(gpgpusim_configdir)-results
transfer_input_files = ../cuda_files.tar.gz, ../watbox.sl40.pqr, ../parboil-cutcp, ../$(gpgpusim_configdir)/
executable = parboil_test.sh
output = parboil.out
error = parboil.err
log = parboil.log

gpgpusim_configdir=SM2_GTX480

queue 1
